### ISSUE TITLE
htmx request gets response blocked by CORS

### ISSUE THREAD

**Issue by nad2040** [Stevens-26/webring#19]
Trying to access endpoint with hx-get.

<img width="884" alt="Screenshot 2023-07-27 at 01 06 43" src="https://github.com/Stevens-26/webring/assets/58147198/17b16a68-37d8-4502-89d0-03181bd07b87">

https://htmx.org/docs/#cors

maybe try adding [Access-Control-Expose-Headers (for response headers)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers)

**Comment by nad2040** [comment]
more complicated than I thought, I guess.

**Comment by nad2040** [comment]
#20

**Comment by ezrizhu** [comment]
Issue was that it was not responding to the OPTIONS preflight requests.
https://github.com/Stevens-26/webring/commit/66a0f430dbed8a13f3b4672f4deae93ebf495eb6 fixes it.
Closing :tada:
